# Generated by Django 4.0.3 on 2022-07-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loveChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=10000)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
    ]
